services:
  - type: web
    name: ozon-bot-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd backend && gunicorn app:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: ENCRYPTION_KEY
        sync: false
      - key: PORT
        value: 8000

  - type: worker
    name: ozon-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd backend && python bot.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: ENCRYPTION_KEY
        sync: false 